FROM golang:1.19 AS builder

RUN mkdir -p /app

COPY /service /app/service
COPY /cmd /app/cmd
COPY /vendor /app/vendor
COPY /go.mod /app/go.mod
COPY /go.sum /app/go.sum

WORKDIR /app

RUN go build -o webapi ./cmd/webapi/

FROM golang:1.19

WORKDIR /app

COPY --from=builder /app/webapi .

EXPOSE 3000

CMD ["./webapi"]