import { doLogin } from "./auth";

export function createUsers(count = 10) {
	const usernames = [
		"Alan Turetta",
		"Ezio Auditore",
		"Nathan Drago",
		"Peter Parco",
		"Elliot Aldo",
		"Adele Adelaidi",
		"Natalie Portaccanto",
		"Leonardo Di Capri",
		"Peppino Di Caprio",
		"Liam Nesso",
		"Bruce Primavera",
		"Bob Dilanio",
		"Dylan Cane",
		"Tarek Iurcich",
		"Fabrizio Di Andrea",
		"Francesco Gucci",
		"Francesco De Gregoriani",
		"Eugenio Anacardi",
		"Lucio Batterista",
		"Lucio Palla",
		"Bjarne Strazuppa",
		"George Hot",
		"Elon Maschera",
		"Jeff Beso",
		"Mark Zucchina",
		"Lex Freeman",
		"Leonel Messia",
		"Cristiano Baldo",
		"Diego Maratoneta",
		"Zinedine Zinedan",
		"Robert De Rossi",
		"Francesco Tutti",
		"Fabio Fabi",
		"Alessandro D'Alessandro",
		"Santina Valletta",
		"Caterina Bene",
		"Carmelo Male",
		"Giacomo Ghepardi",
		"Dante Alghe Di Ieri",
		"Donald Tromba",
		"Mezzosangue",
		"Cara Della Vigna",
		"Pier Paolo Pisolino",
		"Federico Felino",
		"Paulo Di Pavia",
		"Corrado Auggià",
		"Donald Gnu",
		"Ada Lovalacci",
		"Bill Gatto",
		"Linus Timballo",
		"Steve Joint",
		"Steve Kodak",
		"Richard Stallone",
		"Larry Paginato",
		"Sam Alto",
		"Ilya Skater",
		"Andrej Carpa",
		"Silvio Bertolucci",
		"William Shaker",
		"Carlo Cricchio",
		"Antonino Cannaiolo",
		"Bruno Barbiere",
		"Miroslav Closed",
		"Patrizia Peperone",
		"Jake Sparo",
		"Harry Botte",
		"Hermione Gregge",
		"Ronald Frisbee",
		"Chiara Pandori",
		"Rosalba Peppa",
		"Emma Torrone",
		"Emma Pietrola",
		"Jennifer Laurenti",
		"Angelina Giollé",
		"Marilyn Marrone",
		"Margot Robiola",
		"Sophia L'Ore",
		"Penélope Croce",
		"Brigitte Bardo",
		"Sherlock Olmo",
		"Alessandro Mirto",
		"Terence Toes",
		"Pippo",
		"Pluto",
		"Topolino",
		"Paperino",
		"Indiana Pipps",
		"Luke Skyscanner",
		"Fedor Tostosecchi",
		"Elsa Montante",
		"Lev Tolotolo",
		"J.K. Rolling",
		"Biancapece",
	];

	const shuffled = [...usernames].sort(() => Math.random() - 0.5);
	const selectedUsernames = shuffled.slice(0, Math.min(count, shuffled.length));
	return Promise.all(selectedUsernames.map((username) => doLogin(username)));
}
