import { doLogin } from "./auth";

export function createUsers(count = 10) {
	const usernames = [
		"Chris_Cornell",
		"Alan_Turing",
		"Ezio_Auditore",
		"Nathan_Drake",
		"Peter_Parker",
		"Elliot_Alderson",
		"Adele",
		"Natalie_Portman",
		"Leonardo_DiCaprio",
		"Liam_Neeson",
		"Bruce_Springsteen",
		"Bob_Dylan",
		"Fabrizio_De_André",
		"Francesco_Guccini",
		"Lucio_Battisti",
		"Lucio_Dalla",
		"Bjarne_Stroustrup",
		"George_Hotz",
		"Elon_Musk",
		"Jeff_Bezos",
		"Mark_Zuckerberg",
		"Lex_Fridman",
		"Lionel_Messi",
		"CR7",
		"Diego_Maradona",
		"Zinedine_Zidane",
		"Robert_De_Niro",
		"Francesco_Totti",
		"Giacomo_Leopardi",
		"Dante_Alighieri",
		"Donald_Trump",
		"Cara_Delevingne",
		"P_P_Pasolini",
		"Federico_Fellini",
		"Paulo_Dybala",
		"Ada_Lovelace",
		"Bill_Gates",
		"Linus_Torvalds",
		"Steve_Jobs",
		"Richard_Stallman",
		"Larry_Page",
		"Sam_Altman",
		"Ilya_Sutskever",
		"Andrej_Karpathy",
		"Silvio_Berlusconi",
		"William_Shakespeare",
		"Carmelo_Bene",
		"Caterina",
		"Carlo_Cracco",
		"Cannavacciuolo",
		"Bruno_Barbieri",
		"Miroslav_Klose",
		"Jack_Sparrow",
		"Harry_Potter",
		"Hermione_Granger",
		"Ron_Weasley",
		"Jennifer_Lawrence",
		"Angelina_Jolie",
		"Marilyn_Monroe",
		"Margot_Robbie",
		"Sophia_Loren",
		"Penélope_Cruz",
		"Brigitte_Bardot",
		"Sherlock_Holmes",
		"Terence_Hill",
		"Pippo",
		"Pluto",
		"Topolino",
		"Paperino",
		"Indiana_Jones",
		"Luke_Skywalker",
		"Fëdor_Dostoevskij",
		"Elsa_Morante",
		"Lev_Tolstoj",
		"J_K_Rowling",
	];

	const shuffled = [...usernames].sort(() => Math.random() - 0.5);
	const selectedUsernames = shuffled.slice(0, Math.min(count, shuffled.length));
	return Promise.all(selectedUsernames.map((username) => doLogin(username)));
}
